More travis
ome/ome-ansible-molecule pull request #3
Opened 2017-05-03 15:43 UTC by joshmoore

Builds on gh-2 by moving from a "release" (i.e. all roles on galaxy) to a "latest" (i.e. all roles on github) strategy. Note: this is in preparation either for more thorough scanning tools (like https://github.com/nickjj/ansigenome#example-rebuild-output) or our own jenkins job for a "merge" strategy.

2017-05-03 19:19 UTC, joshmoore commented
Current state needs special omero-common handling and then:

 * https://galaxy.ansible.com/openmicroscopy/cadvisor/
 * https://galaxy.ansible.com/openmicroscopy/mysql-backup/
 * https://galaxy.ansible.com/openmicroscopy/system-monitor-agent/

2017-05-04 08:39 UTC, manics requested changes

2017-05-04 08:39 UTC, manics commented on .travis.yml
> -- if [[ -f molecule.yml ]]; then molecule test; fi
I guess not running `molecule test` is one way to ensure travis passes 😃

2017-05-04 08:40 UTC, joshmoore commented on .travis.yml
> -- if [[ -f molecule.yml ]]; then molecule test; fi
Doh.

2017-05-04 08:40 UTC, joshmoore commented on .travis.yml
> -- if [[ -f molecule.yml ]]; then molecule test; fi
Should have known it was too good to be true.

2017-05-05 07:41 UTC, joshmoore commented
An aside while I work on getting this PR green since it may take a while:

```
ome-ansible-molecule-dependencies jamoore$ mkdir vendor; time for x in $(./repos.sh); do git clone --depth=1 git://github.com/openmicroscopy/$x vendor/openmicroscopy.${x##ansible-role-}; done
...
real	0m33.391s
user	0m0.412s
sys	0m1.119s
```
might be a fairly nice way to "get all 

cc: @openmicroscopy/devops

2017-06-13 09:34 UTC, manics requested changes

2017-06-13 09:34 UTC, manics commented on update.py
> +print re.sub("%s.*?%s" % (TAG, TAG), txt, replacement, flags=re.DOTALL),
This script never makes any changes. If I delete some some `- ROLE=...` lines from `.travis.yml`
`diff <(./repos.sh | ./update.py ) .travis.yml` returns no difference.

2017-06-13 10:05 UTC, joshmoore commented on update.py
> +print re.sub("%s.*?%s" % (TAG, TAG), txt, replacement, flags=re.DOTALL),
My simplification apparently is broken. I've rolled it back.

2017-06-13 15:14 UTC, joshmoore commented
Relaunched travis after a previously unseen issue:

```
=================================== FAILURES ===================================
_____________ test_omero_managedrepo[docker://omero-server-newdep] _____________
File = <class 'testinfra.modules.base.GNUFile'>
    def test_omero_managedrepo(File):
        d = File('/OMERO/ManagedRepository')
        assert d.is_directory
        assert d.user == 'omero-server'
        assert d.group == 'importer'
>       assert d.mode == 0o2775
tests/test_default.py:75:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <file /OMERO/ManagedRepository>
    @property
    def mode(self):
        # Supply a base of 8 when parsing an octal integer
        # e.g. int('644', 8) -> 420
>       return int(self.check_output("stat -c %%a %s", self.path), 8)
E       ValueError: invalid literal for int() with base 8: ''
../../../../virtualenv/python2.7.12/lib/python2.7/site-packages/testinfra/modules/file.py:209: ValueError
```

2017-06-13 15:44 UTC, manics commented
```
$ diff <(./repos.sh | ./update.py ) .travis.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  594k  100  594k    0     0   497k      0  0:00:01  0:00:01 --:--:--  497k
26d25
< - ROLE=analysis-tools
30,32d28
< - ROLE=cli-utils
< - ROLE=debug-dumpallvars
< - ROLE=devspace
35d30
< - ROLE=haproxy
44d38
< - ROLE=munin-node
48d41
< - ROLE=nfs-share
53d45
< - ROLE=omero-common
59d50
< - ROLE=omero-web-apps
63,65d53
< - ROLE=prometheus
< - ROLE=prometheus-jmx
< - ROLE=prometheus-node
```

I think the following should work with the current dependencies, are the omitted for a reason?
```
- ROLE=omero-common
- ROLE=omero-web-apps
- ROLE=prometheus-jmx
- ROLE=prometheus-node
```

2017-06-13 15:50 UTC, joshmoore commented
Prometheus only because they are newer than this PR. web-apps I fixed during this repo. common I'm no longer sure about.

2017-06-13 15:52 UTC, manics approved these changes

2017-06-13 18:29 UTC, joshmoore commented
Will handle other repos via follows them.

2017-06-13 18:29 UTC, merged